# Spring Actuator Info App
info.app.title=Metis WebResource Finder
info.app.description=Metis Webresource hash codes finder
info.app.version=1.0.0
info.app.repository=https://github.com/europeana/metis-tools/metis-webresource-finder
info.app.contact.name=Europeana Foundation
info.app.contact.email=info@europeana.eu
info.app.contact.url=www.europeana.eu

# Spring Actuator Management (https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/)
management.endpoints.web.exposure.include=health,info,loggers,metrics,scheduledtasks,beans,mappings
management.endpoints.access.default=read_only
management.endpoint.health.access=read_only
management.endpoint.info.access=read_only
management.endpoint.loggers.access=read_only
management.endpoint.metrics.access=read_only
management.endpoint.scheduledtasks.access=read_only
management.endpoint.beans.access=read_only

## Enables info.app properties
management.info.env.enabled=true

# Spring
spring.application.name=metis-web-resource-finder-app
spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

# Spring open api properties
springdoc.show-actuator=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=eu.europeana.metis.finder.controllers
