<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>eu.europeana.metis</groupId>
        <artifactId>metis-tools</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>metis-statistics-data</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.metis-common-utils>11-SNAPSHOT</version.metis-common-utils>
        <version.metis-common-mongo>11-SNAPSHOT</version.metis-common-mongo>
        <version.spring.boot>3.2.3</version.spring.boot>
        <version.corelib>2.16.10-SNAPSHOT</version.corelib>
        <version.metis-schema>10-SNAPSHOT</version.metis-schema>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>eu.europeana.corelib</groupId>
            <artifactId>corelib-storage</artifactId>
            <version>${version.corelib}</version>
        </dependency>
        <dependency>
            <groupId>eu.europeana.metis</groupId>
            <artifactId>metis-schema</artifactId>
            <version>${version.metis-schema}</version>
            <exclusions>
                <exclusion>
                    <artifactId>xml-apis</artifactId>
                    <groupId>xml-apis</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>eu.europeana.metis</groupId>
            <artifactId>metis-common-utils</artifactId>
            <version>${version.metis-common-utils}</version>
        </dependency>
        <dependency>
            <groupId>eu.europeana.metis</groupId>
            <artifactId>metis-common-mongo</artifactId>
            <version>${version.metis-common-mongo}</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${version.spring.boot}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${version.spring.boot}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
